import type { ChampionKit } from './types';

// Kits are adapted for the bridge arena from the official champion and hero themes.
export const ADDITIONAL_CHAMPIONS: ChampionKit[] = [
  {
    id: 'c_qiyana', name: 'Veyara', title: 'The Prism Regent', basis: 'Qiyana',
    primaryRole: 'Assassin', secondaryRole: 'Fighter', archetype: 'Elemental Assassin',
    hp: 990, ad: 83, armor: 35, mr: 31, aspd: 0.76, range: 1.7,
    passiveDesc: 'Facet Edge: the first hit on an enemy deals bonus damage.',
    skill1: { name: 'Prism Hurl', desc: 'Hurl an elemental blade that wounds and briefly roots.', cooldown: 5, damage: 170, damageType: 'Physical' },
    skill2: { name: 'Facet Dash', desc: 'Dash and gain a fresh element, striking the target.', cooldown: 8, damage: 95, damageType: 'Physical' },
    ultimate: { name: 'Crownfall Surge', desc: 'A sweeping shockwave erupts around clustered enemies.', cooldown: 65, damage: 470, damageType: 'Physical', isUlt: true },
    primaryColor: '#14b8a6', accentColor: '#fde047'
  },
  {
    id: 'c_locke', name: 'Cinderlock', title: 'The Cinder Warden', basis: 'Locke',
    primaryRole: 'Assassin', secondaryRole: 'Mage', archetype: 'Ash Exorcist',
    hp: 1020, ad: 70, armor: 34, mr: 36, aspd: 0.76, range: 2.3,
    passiveDesc: 'Burning Iron: attacks burn wounded enemies with magic.',
    skill1: { name: 'Cinder Spikes', desc: 'Launch a fan of searing ritual nails.', cooldown: 5, damage: 165, damageType: 'Magic' },
    skill2: { name: 'Ash Rush', desc: 'Ignite the soul to rush forward with ash and fire.', cooldown: 9, damage: 120, damageType: 'Magic' },
    ultimate: { name: 'Cinder Verdict', desc: 'Detonate a great ashen exorcism around the target.', cooldown: 60, damage: 445, damageType: 'Magic', isUlt: true },
    primaryColor: '#fb923c', accentColor: '#fef3c7'
  },
  {
    id: 'c_senna', name: 'Solenne', title: 'The Mist Lantern', basis: 'Senna',
    primaryRole: 'Support', secondaryRole: 'Marksman', archetype: 'Relic Cannon Support',
    hp: 940, ad: 78, armor: 31, mr: 35, aspd: 0.67, range: 5.4,
    passiveDesc: 'Waylight: mist souls strengthen the relic cannon.',
    skill1: { name: 'Dusk Lance', desc: 'A light beam damages a foe and heals nearby allies.', cooldown: 6, damage: 135, damageType: 'Physical' },
    skill2: { name: 'Mistbind', desc: 'Dark mist snares the target and nearby enemies.', cooldown: 10, damage: 110, damageType: 'Physical' },
    ultimate: { name: 'Daybreak Veil', desc: 'A wide beam damages enemies and shields allies.', cooldown: 70, damage: 370, damageType: 'Physical', isUlt: true },
    primaryColor: '#14b8a6', accentColor: '#f8fafc'
  },
  {
    id: 'c_largo', name: 'Croakwell', title: 'The Marsh Minstrel', basis: 'Largo',
    primaryRole: 'Support', secondaryRole: 'Tank', archetype: 'Rhythm Support',
    hp: 1240, ad: 57, armor: 44, mr: 42, aspd: 0.64, range: 1.6,
    passiveDesc: 'Lingering Chorus: Croakwell keeps his buffs going for longer.',
    skill1: { name: 'Ribbon Lash', desc: 'Pull and disrupt a foe with a long tongue.', cooldown: 7, damage: 105, damageType: 'Magic' },
    skill2: { name: 'Bogbeat', desc: 'Froglings stomp an area, interrupting enemies.', cooldown: 10, damage: 110, damageType: 'Magic' },
    ultimate: { name: 'Marsh Anthem', desc: 'A luminous song heals and empowers the entire team.', cooldown: 65, damage: 160, damageType: 'Magic', isUlt: true },
    primaryColor: '#84cc16', accentColor: '#facc15'
  },
  {
    id: 'c_shadowfiend', name: 'Soulscourge', title: 'The Gloom Harvester', basis: 'Shadow Fiend',
    primaryRole: 'Mage', secondaryRole: 'Assassin', archetype: 'Soul Nuker',
    hp: 920, ad: 84, armor: 30, mr: 32, aspd: 0.73, range: 5.0,
    passiveDesc: 'Soul Hoard: fallen foes feed his damage.',
    skill1: { name: 'Gloom Raze', desc: 'Raze the earth in front of him with dark fire.', cooldown: 5, damage: 175, damageType: 'Magic' },
    skill2: { name: 'Soul Draw', desc: 'Gather nearby souls for a surge of damage.', cooldown: 10, damage: 115, damageType: 'Magic' },
    ultimate: { name: 'Dirge Wave', desc: 'Release concentric soul waves that terrify nearby enemies.', cooldown: 75, damage: 490, damageType: 'Magic', isUlt: true },
    primaryColor: '#7f1d1d', accentColor: '#fb7185'
  },
  {
    id: 'c_earthshaker', name: 'Stonewake', title: 'The Faultline Warden', basis: 'Earthshaker',
    primaryRole: 'Tank', secondaryRole: 'Support', archetype: 'Seismic Initiator',
    hp: 1380, ad: 69, armor: 53, mr: 40, aspd: 0.60, range: 1.5,
    passiveDesc: 'Stone Pulse: every spell sends a tremor through nearby foes.',
    skill1: { name: 'Faultline', desc: 'Split the ground with a long stunning ridge.', cooldown: 9, damage: 145, damageType: 'Magic' },
    skill2: { name: 'Runic Maul', desc: 'Empower the next blow and stun a nearby enemy.', cooldown: 8, damage: 125, damageType: 'Physical' },
    ultimate: { name: 'Quake Chorus', desc: 'A giant quake echoes through every enemy in the cluster.', cooldown: 75, damage: 410, damageType: 'Magic', isUlt: true },
    primaryColor: '#a16207', accentColor: '#facc15'
  },
  { id: 'c_mirehook', name: 'Mirehook', title: 'The Bog Butcher', basis: 'Pudge',
    primaryRole: 'Tank', secondaryRole: 'Fighter', archetype: 'Pick Initiator',
    hp: 1420, ad: 76, armor: 49, mr: 39, aspd: 0.58, range: 1.5,
    passiveDesc: 'Carrion Feast: takedowns thicken his hide.',
    skill1: { name: 'Barbed Chain', desc: 'A dodgeable hook drags the first target closer.', cooldown: 10, damage: 150, damageType: 'Physical' },
    skill2: { name: 'Rot Cloud', desc: 'Poison nearby foes and endure the counterattack.', cooldown: 11, damage: 95, damageType: 'Magic' },
    ultimate: { name: 'Feast Lock', desc: 'Pin and drain one nearby target.', cooldown: 70, damage: 440, damageType: 'Physical', isUlt: true },
    primaryColor: '#54704c', accentColor: '#b5d36b' },
  { id: 'c_nullweaver', name: 'Nullweaver', title: 'The Void Cartographer', basis: 'Enigma',
    primaryRole: 'Mage', secondaryRole: 'Support', archetype: 'Zone Control',
    hp: 980, ad: 68, armor: 31, mr: 40, aspd: 0.65, range: 5,
    passiveDesc: 'Void Echo: spells pull foes toward unstable ground.',
    skill1: { name: 'Gravitic Pin', desc: 'A dodgeable orb pins a target in place.', cooldown: 8, damage: 140, damageType: 'Magic' },
    skill2: { name: 'Dark Filament', desc: 'Lay a damaging field under clustered foes.', cooldown: 11, damage: 115, damageType: 'Magic' },
    ultimate: { name: 'Singularity Well', desc: 'Pull a team together and crush the center.', cooldown: 80, damage: 420, damageType: 'Magic', isUlt: true },
    primaryColor: '#34205f', accentColor: '#a78bfa' },
  { id: 'c_voltgrip', name: 'Voltgrip', title: 'The Storm Automaton', basis: 'Blitzcrank',
    primaryRole: 'Support', secondaryRole: 'Tank', archetype: 'Catch Support',
    hp: 1280, ad: 70, armor: 47, mr: 39, aspd: 0.61, range: 1.5,
    passiveDesc: 'Capacitor: shields flare when danger rises.',
    skill1: { name: 'Arc Grapple', desc: 'A narrow dodgeable grapple pulls an enemy.', cooldown: 12, damage: 145, damageType: 'Magic' },
    skill2: { name: 'Charged Fist', desc: 'Knock up the caught target.', cooldown: 8, damage: 100, damageType: 'Physical' },
    ultimate: { name: 'Thunder Dome', desc: 'A close electrical burst stuns nearby foes.', cooldown: 66, damage: 380, damageType: 'Magic', isUlt: true },
    primaryColor: '#9a701e', accentColor: '#fde047' },
  { id: 'c_aetherbolt', name: 'Aetherbolt', title: 'The Relic Runner', basis: 'Ezreal',
    primaryRole: 'Marksman', secondaryRole: 'Mage', archetype: 'Mobile Poke',
    hp: 930, ad: 91, armor: 30, mr: 31, aspd: 0.76, range: 5,
    passiveDesc: 'Quick Study: precise shots reward mobility.',
    skill1: { name: 'Relic Bolt', desc: 'A fast dodgeable shot through the lane.', cooldown: 5, damage: 170, damageType: 'Magic' },
    skill2: { name: 'Phase Skip', desc: 'Blink to the side and mark an enemy.', cooldown: 12, damage: 80, damageType: 'Magic' },
    ultimate: { name: 'Horizon Lance', desc: 'A wide piercing beam crosses the fight.', cooldown: 72, damage: 430, damageType: 'Magic', isUlt: true },
    primaryColor: '#1d6caa', accentColor: '#67e8f9' },
  { id: 'c_corsara', name: 'Corsara', title: 'The Scarlet Privateer', basis: 'Miss Fortune',
    primaryRole: 'Marksman', secondaryRole: 'Mage', archetype: 'Area Barrage',
    hp: 970, ad: 96, armor: 30, mr: 31, aspd: 0.73, range: 5,
    passiveDesc: 'Fresh Target: switching targets rewards quick hands.',
    skill1: { name: 'Ricochet Round', desc: 'A dodgeable round bursts into nearby foes.', cooldown: 6, damage: 160, damageType: 'Physical' },
    skill2: { name: 'Saltstorm', desc: 'Rain shot over an area and slow foes.', cooldown: 12, damage: 100, damageType: 'Magic' },
    ultimate: { name: 'Broadside Waltz', desc: 'Spray a visible cone of cannon fire.', cooldown: 76, damage: 460, damageType: 'Physical', isUlt: true },
    primaryColor: '#9f263d', accentColor: '#fb7185' },
  { id: 'c_brewmaw', name: 'Brewmaw', title: 'The Cask Colossus', basis: 'Gragas',
    primaryRole: 'Tank', secondaryRole: 'Mage', archetype: 'Disruptive Frontline',
    hp: 1380, ad: 74, armor: 47, mr: 43, aspd: 0.61, range: 1.5,
    passiveDesc: 'Hearty Brew: casting restores a little health.',
    skill1: { name: 'Bursting Cask', desc: 'A dodgeable cask explodes among clustered foes.', cooldown: 8, damage: 155, damageType: 'Magic' },
    skill2: { name: 'Barrel Rush', desc: 'Lunge into a target and knock them aside.', cooldown: 10, damage: 105, damageType: 'Magic' },
    ultimate: { name: 'Grand Vintage', desc: 'A huge cask scatters the enemy formation.', cooldown: 75, damage: 390, damageType: 'Magic', isUlt: true },
    primaryColor: '#783e20', accentColor: '#f59e0b' },
  { id: 'c_wraithhook', name: 'Wraithhook', title: 'The Lantern Collector', basis: 'Thresh',
    primaryRole: 'Support', secondaryRole: 'Tank', archetype: 'Chain Control',
    hp: 1160, ad: 72, armor: 43, mr: 38, aspd: 0.65, range: 3,
    passiveDesc: 'Lantern Souls: gathers protection from fallen foes.',
    skill1: { name: 'Spectral Harpoon', desc: 'A dodgeable spectral hook pulls a foe.', cooldown: 11, damage: 140, damageType: 'Magic' },
    skill2: { name: 'Guiding Lantern', desc: 'Shield nearby allies and push a foe away.', cooldown: 12, damage: 70, damageType: 'Magic' },
    ultimate: { name: 'Lantern Prison', desc: 'Enclose nearby enemies in a slowing spirit cage.', cooldown: 75, damage: 370, damageType: 'Magic', isUlt: true },
    primaryColor: '#155e58', accentColor: '#5eead4' }
];
