import type { ChampionKit } from './types';

// Kits are adapted for the bridge arena from the official champion and hero themes.
export const ADDITIONAL_CHAMPIONS: ChampionKit[] = [
  {
    id: 'c_qiyana', name: 'Veyara', displayName: 'Crownfetti', title: 'The Prism Regent', basis: 'Qiyana',
    primaryRole: 'Assassin', secondaryRole: 'Fighter', archetype: 'Elemental Assassin',
    hp: 990, ad: 83, armor: 35, mr: 31, aspd: 0.76, range: 1.7,
    passiveDesc: 'Facet Edge: the first hit on an enemy deals bonus damage.',
    skill1: { name: 'Prism Hurl', desc: 'Hurl an elemental blade that wounds and briefly roots.', cooldown: 5, damage: 170, damageType: 'Physical' },
    skill2: { name: 'Facet Dash', desc: 'Dash and gain a fresh element, striking the target.', cooldown: 8, damage: 95, damageType: 'Physical' },
    ultimate: { name: 'Crownfall Surge', desc: 'A sweeping shockwave erupts around clustered enemies.', cooldown: 65, damage: 470, damageType: 'Physical', isUlt: true },
    primaryColor: '#14b8a6', accentColor: '#fde047'
  },
  {
    id: 'c_locke', name: 'Cinderbloom', displayName: 'Sootcase', title: 'The Cinder Warden', basis: 'Locke',
    primaryRole: 'Assassin', secondaryRole: 'Fighter', archetype: 'Ash Blade Exorcist',
    hp: 1040, ad: 74, armor: 36, mr: 36, aspd: 0.78, range: 1.4,
    passiveDesc: 'Burning Iron: melee strikes burn wounded enemies with magic.',
    skill1: { name: 'Cinder Sequence', desc: 'Lunge to a target with ash blades, ignite on the second cast, then critically strike in close melee combat.', cooldown: 5, damage: 165, damageType: 'Magic' },
    skill2: { name: 'Ash Veil', desc: 'Become invisible for a few seconds and gain swift movement until striking from shadows or taking damage.', cooldown: 9, damage: 0, damageType: 'Magic' },
    ultimate: { name: 'Cinder Verdict', desc: 'Detonate a great ashen exorcism around the target.', cooldown: 60, damage: 445, damageType: 'Magic', isUlt: true },
    primaryColor: '#fb923c', accentColor: '#fef3c7'
  },
  {
    id: 'c_senna', name: 'Solenne', displayName: 'Sennova', title: 'The Mist Lantern', basis: 'Senna',
    primaryRole: 'Support', secondaryRole: 'Marksman', archetype: 'Relic Cannon Support',
    hp: 940, ad: 78, armor: 31, mr: 35, aspd: 0.67, range: 5.4,
    passiveDesc: 'Waylight: mist souls strengthen the relic cannon.',
    skill1: { name: 'Dusk Lance', desc: 'A light beam damages a foe and heals nearby allies.', cooldown: 6, damage: 135, damageType: 'Physical' },
    skill2: { name: 'Mistbind', desc: 'Dark mist snares the target and nearby enemies.', cooldown: 10, damage: 110, damageType: 'Physical' },
    ultimate: { name: 'Daybreak Veil', desc: 'A wide beam damages enemies and shields allies.', cooldown: 70, damage: 370, damageType: 'Physical', isUlt: true },
    primaryColor: '#14b8a6', accentColor: '#f8fafc'
  },
  {
    id: 'c_largo', name: 'Croakwell', displayName: 'Basso Croak', title: 'The Marsh Minstrel', basis: 'Largo',
    primaryRole: 'Support', secondaryRole: 'Tank', archetype: 'Rhythm Support',
    hp: 1240, ad: 57, armor: 44, mr: 42, aspd: 0.64, range: 1.6,
    passiveDesc: 'Lingering Chorus: Croakwell keeps his buffs going for longer.',
    skill1: { name: 'Ribbon Lash', desc: 'Pull and disrupt a foe with a long tongue.', cooldown: 7, damage: 105, damageType: 'Magic' },
    skill2: { name: 'Bogbeat', desc: 'Froglings stomp an area, interrupting enemies.', cooldown: 10, damage: 110, damageType: 'Magic' },
    ultimate: { name: 'Marsh Anthem', desc: 'A luminous song heals and empowers the entire team.', cooldown: 65, damage: 160, damageType: 'Magic', isUlt: true },
    primaryColor: '#84cc16', accentColor: '#facc15'
  },
  {
    id: 'c_shadowfiend', name: 'Soulscourge', displayName: 'Razeberry', title: 'The Gloom Harvester', basis: 'Shadow Fiend',
    primaryRole: 'Mage', secondaryRole: 'Assassin', archetype: 'Soul Nuker',
    combatRoles: { Nuker: 3, Disabler: 2, Carry: 1, Pusher: 2 },
    hp: 920, ad: 84, armor: 30, mr: 32, aspd: 0.73, range: 5.0,
    passiveDesc: 'Soul Hoard: fallen foes feed his damage.',
    skill1: { name: 'Gloom Raze', desc: 'Raze the earth in front of him with dark fire.', cooldown: 5, damage: 175, damageType: 'Magic' },
    skill2: { name: 'Soul Draw', desc: 'Gather nearby souls for a surge of damage.', cooldown: 10, damage: 115, damageType: 'Magic' },
    ultimate: { name: 'Dirge Wave', desc: 'Release concentric soul waves that terrify nearby enemies.', cooldown: 75, damage: 490, damageType: 'Magic', isUlt: true },
    primaryColor: '#7f1d1d', accentColor: '#fb7185'
  },
  {
    id: 'c_earthshaker', name: 'Stonewake', displayName: 'Quakewell', title: 'The Faultline Warden', basis: 'Earthshaker',
    primaryRole: 'Tank', secondaryRole: 'Support', archetype: 'Seismic Initiator',
    combatRoles: { Support: 1, Nuker: 1, Disabler: 3, Jungler: 0, Durable: 2, Pusher: 0, Initiator: 3 },
    hp: 1380, ad: 69, armor: 53, mr: 40, aspd: 0.60, range: 1.5,
    passiveDesc: 'Stone Pulse: every spell sends a tremor through nearby foes.',
    skill1: { name: 'Faultline', desc: 'Split the ground with a long stunning ridge.', cooldown: 9, damage: 145, damageType: 'Magic' },
    skill2: { name: 'Runic Maul', desc: 'Empower the next blow and stun a nearby enemy.', cooldown: 8, damage: 125, damageType: 'Physical' },
    ultimate: { name: 'Quake Chorus', desc: 'A giant quake echoes through every enemy in the cluster.', cooldown: 75, damage: 410, damageType: 'Magic', isUlt: true },
    primaryColor: '#a16207', accentColor: '#facc15'
  },
  { id: 'c_mirehook', name: 'Mirehook', displayName: 'Rotisserie', title: 'The Bog Butcher', basis: 'Pudge',
    primaryRole: 'Tank', secondaryRole: 'Fighter', archetype: 'Pick Initiator',
    hp: 1420, ad: 76, armor: 49, mr: 39, aspd: 0.58, range: 1.5,
    passiveDesc: 'Carrion Feast: takedowns thicken his hide.',
    skill1: { name: 'Barbed Chain', desc: 'A dodgeable hook drags the first target closer.', cooldown: 10, damage: 150, damageType: 'Physical' },
    skill2: { name: 'Rot Cloud', desc: 'Poison nearby foes and endure the counterattack.', cooldown: 11, damage: 95, damageType: 'Magic' },
    ultimate: { name: 'Feast Lock', desc: 'Pin and drain one nearby target.', cooldown: 70, damage: 440, damageType: 'Physical', isUlt: true },
    primaryColor: '#54704c', accentColor: '#b5d36b' },
  { id: 'c_nullweaver', name: 'Nullweaver', displayName: 'Midnight Equation', title: 'The Void Cartographer', basis: 'Enigma',
    primaryRole: 'Mage', secondaryRole: 'Support', archetype: 'Zone Control',
    combatRoles: { Support: 1, Nuker: 2, Disabler: 3, Initiator: 2, Pusher: 1 },
    hp: 980, ad: 68, armor: 31, mr: 40, aspd: 0.65, range: 5,
    passiveDesc: 'Void Echo: spells pull foes toward unstable ground.',
    skill1: { name: 'Gravitic Pin', desc: 'A dodgeable orb pins a target in place.', cooldown: 8, damage: 140, damageType: 'Magic' },
    skill2: { name: 'Dark Filament', desc: 'Lay a damaging field under clustered foes.', cooldown: 11, damage: 115, damageType: 'Magic' },
    ultimate: { name: 'Singularity Well', desc: 'Channel a compact black hole for 3.2 seconds, pulling enemies within 105 range. Crowd control interrupts the channel.', cooldown: 80, damage: 420, damageType: 'Magic', isUlt: true },
    primaryColor: '#34205f', accentColor: '#a78bfa' },
  { id: 'c_voltgrip', name: 'Voltgrip', displayName: 'Plugsy', title: 'The Storm Automaton', basis: 'Blitzcrank',
    primaryRole: 'Support', secondaryRole: 'Tank', archetype: 'Catch Support',
    hp: 1280, ad: 70, armor: 47, mr: 39, aspd: 0.61, range: 1.5,
    passiveDesc: 'Capacitor: shields flare when danger rises.',
    skill1: { name: 'Arc Grapple', desc: 'A narrow dodgeable grapple pulls an enemy.', cooldown: 12, damage: 145, damageType: 'Magic' },
    skill2: { name: 'Charged Fist', desc: 'Knock up the caught target.', cooldown: 8, damage: 100, damageType: 'Physical' },
    ultimate: { name: 'Thunder Dome', desc: 'A close electrical burst stuns nearby foes.', cooldown: 66, damage: 380, damageType: 'Magic', isUlt: true },
    primaryColor: '#9a701e', accentColor: '#fde047' },
  { id: 'c_aetherbolt', name: 'Aetherbolt', displayName: 'Relic Rick', title: 'The Relic Runner', basis: 'Ezreal',
    primaryRole: 'Marksman', secondaryRole: 'Mage', archetype: 'Mobile Poke',
    hp: 930, ad: 91, armor: 30, mr: 31, aspd: 0.76, range: 5,
    passiveDesc: 'Quick Study: precise shots reward mobility.',
    skill1: { name: 'Relic Bolt', desc: 'A fast dodgeable shot through the lane.', cooldown: 5, damage: 170, damageType: 'Magic' },
    skill2: { name: 'Phase Skip', desc: 'Blink to the side and mark an enemy.', cooldown: 12, damage: 80, damageType: 'Magic' },
    ultimate: { name: 'Horizon Lance', desc: 'A wide piercing beam crosses the fight.', cooldown: 72, damage: 430, damageType: 'Magic', isUlt: true },
    primaryColor: '#1d6caa', accentColor: '#67e8f9' },
  { id: 'c_corsara', name: 'Corsara', displayName: 'Bounty Belle', title: 'The Scarlet Privateer', basis: 'Miss Fortune',
    primaryRole: 'Marksman', secondaryRole: 'Mage', archetype: 'Area Barrage',
    hp: 970, ad: 96, armor: 30, mr: 31, aspd: 0.73, range: 5,
    passiveDesc: 'Fresh Target: switching targets rewards quick hands.',
    skill1: { name: 'Ricochet Round', desc: 'A dodgeable round bursts into nearby foes.', cooldown: 6, damage: 160, damageType: 'Physical' },
    skill2: { name: 'Saltstorm', desc: 'Rain shot over an area and slow foes.', cooldown: 12, damage: 100, damageType: 'Magic' },
    ultimate: { name: 'Broadside Waltz', desc: 'Channel a fixed cone of cannon fire in six waves over three seconds. Crowd control interrupts the channel.', cooldown: 76, damage: 360, damageType: 'Physical', isUlt: true },
    primaryColor: '#9f263d', accentColor: '#fb7185' },
  { id: 'c_brewmaw', name: 'Brewmaw', displayName: 'Kegory', title: 'The Cask Colossus', basis: 'Gragas',
    primaryRole: 'Tank', secondaryRole: 'Mage', archetype: 'Disruptive Frontline',
    hp: 1380, ad: 74, armor: 47, mr: 43, aspd: 0.61, range: 1.5,
    passiveDesc: 'Hearty Brew: casting restores a little health.',
    skill1: { name: 'Bursting Cask', desc: 'A dodgeable cask explodes among clustered foes.', cooldown: 8, damage: 155, damageType: 'Magic' },
    skill2: { name: 'Barrel Rush', desc: 'Lunge into a target and knock them aside.', cooldown: 10, damage: 105, damageType: 'Magic' },
    ultimate: { name: 'Grand Vintage', desc: 'A huge cask scatters the enemy formation.', cooldown: 75, damage: 390, damageType: 'Magic', isUlt: true },
    primaryColor: '#783e20', accentColor: '#f59e0b' },
  { id: 'c_wraithhook', name: 'Wraithhook', displayName: 'Hooklyn', title: 'The Lantern Collector', basis: 'Thresh',
    primaryRole: 'Support', secondaryRole: 'Tank', archetype: 'Chain Control',
    hp: 1160, ad: 72, armor: 43, mr: 38, aspd: 0.65, range: 3,
    passiveDesc: 'Lantern Souls: gathers protection from fallen foes.',
    skill1: { name: 'Spectral Harpoon', desc: 'A dodgeable spectral hook pulls a foe.', cooldown: 11, damage: 140, damageType: 'Magic' },
    skill2: { name: 'Guiding Lantern', desc: 'Shield nearby allies and push a foe away.', cooldown: 12, damage: 70, damageType: 'Magic' },
    ultimate: { name: 'Lantern Prison', desc: 'Enclose nearby enemies in a slowing spirit cage.', cooldown: 75, damage: 370, damageType: 'Magic', isUlt: true },
    primaryColor: '#155e58', accentColor: '#5eead4' },
  { id: 'c_invoker', name: 'Kaelen', displayName: 'Arsenaldo', title: 'The Arsenal Prodigy', basis: 'Invoker',
    primaryRole: 'Mage', secondaryRole: 'Support', archetype: 'Arsenal Mage',
    hp: 910, ad: 62, armor: 29, mr: 34, aspd: 0.70, range: 5.2,
    passiveDesc: 'Conflux (R): Combine the last three Ice, Wind, and Fire orbs into an invoked spell. Two invoked abilities are held in FIFO order on D and F; cooldown falls to 3s / 2s / 1s / 0s at levels 1 / 7 / 13 / 18.',
    skill1: { name: 'Orb of Ice', desc: 'Gather an Ice orb into the three-orb FIFO. Each held Ice orb grants 0.2 health regeneration per second at rank 1, scaling by 25% each rank; its bonus ends when it leaves the FIFO.', cooldown: 0, damage: 0, damageType: 'Magic', targeting: 'none' },
    skill2: { name: 'Orb of Wind', desc: 'Gather a Wind orb into the three-orb FIFO. Each held Wind orb grants 1 movement speed at rank 1, scaling by 25% each rank; its bonus ends when it leaves the FIFO.', cooldown: 0, damage: 0, damageType: 'Magic', targeting: 'none' },
    ultimate: { name: 'Orb of Fire', desc: 'Gather a Fire orb into the three-orb FIFO. Each held Fire orb grants 1% spell amp and damage amp at rank 1, scaling by 25% each rank; its bonus ends when it leaves the FIFO.', cooldown: 0, damage: 0, damageType: 'Magic', targeting: 'none' },
    primaryColor: '#eab308', accentColor: '#f97316' },
  { id: 'c_hwei', name: 'Hweilin', displayName: 'Inkognito', title: 'The Ink Visionary', basis: 'Hwei',
    primaryRole: 'Mage', secondaryRole: 'Support', archetype: 'Artistic Painter',
    hp: 920, ad: 58, armor: 28, mr: 33, aspd: 0.69, range: 5.0,
    passiveDesc: 'Signature Pigment: Landing contrasting paint strokes triggers a radiant explosion on foes.',
    skill1: { name: 'Molten Splatter', desc: 'Flings an arc of fiery paint that erupts on impact.', cooldown: 6, damage: 175, damageType: 'Magic' },
    skill2: { name: 'Gleaming Wash', desc: 'Paints an energizing river giving movement speed and shields to allies.', cooldown: 10, damage: 95, damageType: 'Magic' },
    ultimate: { name: 'Vortex of Torment', desc: 'Expands a tragic bloom of spreading paint that grips and detonates.', cooldown: 75, damage: 450, damageType: 'Magic', isUlt: true },
    primaryColor: '#06b6d4', accentColor: '#a855f7' },
  { id: 'c_jayce', name: 'Jaxon', displayName: 'Hexley', title: 'The Hextech Vanguard', basis: 'Jayce',
    primaryRole: 'Fighter', secondaryRole: 'Marksman', archetype: 'Stance Skirmisher',
    hp: 1050, ad: 88, armor: 38, mr: 35, aspd: 0.75, range: 3.5,
    passiveDesc: 'Transform Capacitor: Shifting weapons grants immediate movement speed and armor pen.',
    skill1: { name: 'Shock Blast Plasma', desc: 'Fires an accelerated plasma orb through an acceleration field.', cooldown: 6, damage: 190, damageType: 'Physical' },
    skill2: { name: 'Thundering Leap', desc: 'Leaps into the fray with hammer charged, smashing the ground.', cooldown: 9, damage: 140, damageType: 'Physical' },
    ultimate: { name: 'Mercury Overdrive', desc: 'Swaps into cannon mode unleashing rapid fire bursts and shredding defenses.', cooldown: 45, damage: 400, damageType: 'Physical', isUlt: true },
    primaryColor: '#0284c7', accentColor: '#e0f2fe' },
  { id: 'c_vi', name: 'Valerie', displayName: 'Knuckleberry', title: 'The Piltover Enforcer', basis: 'Vi',
    primaryRole: 'Fighter', secondaryRole: 'Assassin', archetype: 'Heavy Bruiser',
    hp: 1120, ad: 86, armor: 42, mr: 36, aspd: 0.72, range: 1.6,
    passiveDesc: 'Blast Shield: Landing abilities grants a heavy kinetic protective shield.',
    skill1: { name: 'Vault Breaker Punch', desc: 'Charges forward delivering an armor-shattering heavy punch.', cooldown: 8, damage: 165, damageType: 'Physical' },
    skill2: { name: 'Denting Impact', desc: 'Successive blows crack enemy armor and grant bonus attack speed.', cooldown: 6, damage: 110, damageType: 'Physical' },
    ultimate: { name: 'Cease and Desist Slam', desc: 'Locks onto a priority enemy target, charges through obstacles and slams them downward.', cooldown: 70, damage: 460, damageType: 'Physical', isUlt: true },
    primaryColor: '#ec4899', accentColor: '#f43f5e' },
  { id: 'c_jinx', name: 'Jinxy', displayName: 'Boomie', title: 'The Loose Cannon', basis: 'Jinx',
    primaryRole: 'Marksman', secondaryRole: 'Assassin', archetype: 'Hypercarry Marksman',
    hp: 880, ad: 96, armor: 28, mr: 30, aspd: 0.78, range: 5.6,
    passiveDesc: 'Get Excited!: Scored takedowns grant massive decaying movement speed and attack speed.',
    skill1: { name: 'Fishbones Rockets', desc: 'Swaps to rocket launcher firing explosive long-range area damage.', cooldown: 4, damage: 175, damageType: 'Physical' },
    skill2: { name: 'Shock Pistols Zap', desc: 'Fires an electric zapper beam that damages and heavily slows the first enemy.', cooldown: 7, damage: 125, damageType: 'Physical' },
    ultimate: { name: 'Super Mega Rocket', desc: 'Fires a colossal global missile that executes enemies based on missing health.', cooldown: 70, damage: 490, damageType: 'Physical', isUlt: true },
    primaryColor: '#3b82f6', accentColor: '#f43f5e' },
  { id: 'c_puck', name: 'Paxi', displayName: 'Fizzlewing', title: 'The Faerie Dragon', basis: 'Puck',
    primaryRole: 'Mage', secondaryRole: 'Assassin', archetype: 'Elusive Playmaker',
    hp: 890, ad: 64, armor: 30, mr: 34, aspd: 0.74, range: 4.8,
    passiveDesc: 'Phase Shift Reflex: Automatically evades lethal burst by vanishing between dimensions.',
    skill1: { name: 'Illusory Orb Jaunt', desc: 'Launches an orb toward the selected position or facing direction; Paxi can jaunt to its current position.', cooldown: 7, damage: 160, damageType: 'Magic', targeting: 'ground' },
    skill2: { name: 'Waning Rift Silence', desc: 'Blasts a wave of fairy dust silencing nearby enemies in a circle.', cooldown: 9, damage: 120, damageType: 'Magic' },
    ultimate: { name: 'Dream Coil Tether', desc: 'Tethers enemy champions to an astral spring, stunning and tearing them if broken.', cooldown: 65, damage: 410, damageType: 'Magic', isUlt: true },
    primaryColor: '#10b981', accentColor: '#38bdf8' },
  { id: 'c_batrider', name: 'Batrix', displayName: 'Wickety', title: 'The Flame Rider', basis: 'Batrider',
    primaryRole: 'Fighter', secondaryRole: 'Mage', archetype: 'Aerial Initiator',
    hp: 1100, ad: 72, armor: 41, mr: 38, aspd: 0.68, range: 3.2,
    passiveDesc: 'Sticky Napalm: Each layer of napalm increases fire damage taken by enemies.',
    skill1: { name: 'Firefly Scorched Path', desc: 'Takes flight over terrain leaving a deadly burning fire path.', cooldown: 9, damage: 150, damageType: 'Magic' },
    skill2: { name: 'Flamebreak Grenade', desc: 'Hurls an explosive cocktail knocking back enemies in the area.', cooldown: 11, damage: 110, damageType: 'Magic' },
    ultimate: { name: 'Flaming Lasso Drag', desc: 'Snag an enemy champion with a blazing lasso and drags them into the team.', cooldown: 75, damage: 380, damageType: 'Magic', isUlt: true },
    primaryColor: '#f97316', accentColor: '#ef4444' },
  { id: 'c_bristleback', name: 'Quillback', displayName: 'Hedgehoggin', title: 'The Barbed Brawler', basis: 'Bristleback',
    primaryRole: 'Tank', secondaryRole: 'Fighter', archetype: 'Frontline Sponge',
    hp: 1480, ad: 74, armor: 56, mr: 44, aspd: 0.62, range: 1.5,
    passiveDesc: 'Bristled Carapace: Reduces incoming damage from the rear and sides, auto-spraying quills.',
    skill1: { name: 'Viscous Nasal Slime', desc: 'Covers enemy in sticky goo, slowing and reducing their armor.', cooldown: 5, damage: 90, damageType: 'Physical' },
    skill2: { name: 'Quill Spray Nova', desc: 'Shoots a circle of poisonous quills dealing stacking damage.', cooldown: 4, damage: 130, damageType: 'Physical' },
    ultimate: { name: 'Warpath Stampede', desc: 'Each spell cast increases movement speed and attack damage dramatically.', cooldown: 50, damage: 360, damageType: 'Physical', isUlt: true },
    primaryColor: '#84cc16', accentColor: '#65a30d' },
  { id: 'c_io', name: 'Aetheris', displayName: 'Orbiton', title: 'The Harmonic Spark', basis: 'Io',
    primaryRole: 'Support', secondaryRole: 'Mage', archetype: 'Tether Enhancer',
    hp: 950, ad: 52, armor: 30, mr: 38, aspd: 0.65, range: 4.8,
    passiveDesc: 'Harmonic Link: Automatically forms a visible, persistent tether with the nearest living ally within 280 arena units.',
    skill1: { name: 'Spirits Orbit Array', desc: 'Summons five bright spirits that orbit Aetheris. Each shot launches a spirit; it bursts on an enemy avatar hit and splashes nearby foes.', cooldown: 8, damage: 160, damageType: 'Magic', targeting: 'unit' },
    skill2: { name: 'Overcharge Surge', desc: 'Tethers the nearest nearby ally in a bright aura, granting a shield and increased attack damage for 5 seconds.', cooldown: 12, damage: 0, damageType: 'Magic', targeting: 'ally' },
    ultimate: { name: 'Resonant Convergence', desc: 'Tethers every living allied avatar within 260 arena units for 5 seconds at rank 1, increasing by 1 second per rank up to 8 seconds at rank 4. Grants each tethered ally an immediate heal and shield.', cooldown: 70, damage: 0, damageType: 'Magic', isUlt: true, targeting: 'self' },
    primaryColor: '#38bdf8', accentColor: '#e0f2fe' },
  { id: 'c_lulu', name: 'Faelith', displayName: 'Pixabelle', title: 'The Briar Sprite', basis: 'Lulu',
    primaryRole: 'Support', secondaryRole: 'Mage', archetype: 'Enchanter Disabler',
    combatRoles: { Support: 3, Disabler: 2, Nuker: 1, Durable: 0 },
    hp: 940, ad: 54, armor: 29, mr: 37, aspd: 0.65, range: 4.7,
    passiveDesc: 'Briar Spark: a small familiar adds a little damage to basic attacks.',
    skill1: { name: 'Glimmerthorn', desc: 'Fire a dodgeable slowing thorn through a target.', cooldown: 7, damage: 130, damageType: 'Magic' },
    skill2: { name: 'Mothspell', desc: 'Turn a threatening enemy into a harmless moth briefly and shield a nearby ally.', cooldown: 12, damage: 0, damageType: 'Magic' },
    ultimate: { name: 'Wildheart Bloom', desc: 'Grow and shield the lowest-health ally, knocking up enemies around them.', cooldown: 78, damage: 95, damageType: 'Magic', isUlt: true },
    primaryColor: '#a855f7', accentColor: '#bef264' },
  { id: 'c_silencer', name: 'Oathmute', displayName: 'Muffleton', title: 'The Last Scribe', basis: 'Silencer',
    primaryRole: 'Mage', secondaryRole: 'Support', archetype: 'Silence Disabler',
    combatRoles: { Disabler: 3, Support: 2, Nuker: 2 },
    hp: 985, ad: 62, armor: 30, mr: 42, aspd: 0.67, range: 4.9,
    passiveDesc: 'Quiet Ink: repeated spells make enemy casters easier to track.',
    skill1: { name: 'Inkblight', desc: 'A dodgeable ink bolt damages a target and nearby enemies.', cooldown: 8, damage: 145, damageType: 'Magic' },
    skill2: { name: 'Last Edict', desc: 'Silence one nearby enemy, preventing ability casts and channels.', cooldown: 11, damage: 70, damageType: 'Magic' },
    ultimate: { name: 'Stillness Decree', desc: 'Briefly silence all living enemies; it can interrupt channeled abilities.', cooldown: 85, damage: 0, damageType: 'Magic', isUlt: true },
    primaryColor: '#4338ca', accentColor: '#ddd6fe' },
  { id: 'c_wukong_lol', name: 'Cloudtail', displayName: 'Stafford', title: 'The Miststaff Brother', basis: 'Wukong (League)',
    primaryRole: 'Fighter', secondaryRole: 'Assassin', archetype: 'Trickster Initiator',
    combatRoles: { Initiator: 3, Disabler: 2, Escape: 2, Jungler: 2 },
    hp: 1110, ad: 82, armor: 41, mr: 34, aspd: 0.75, range: 1.8,
    passiveDesc: 'Brotherly Rivalry: Cloudtail excels at close, moving fights.',
    skill1: { name: 'Longstaff Crack', desc: 'Strike with an extended staff and crack armor.', cooldown: 6, damage: 150, damageType: 'Physical' },
    skill2: { name: 'Mist Double', desc: 'Leave a visible decoy and slip sideways under a brief veil.', cooldown: 13, damage: 0, damageType: 'Magic' },
    ultimate: { name: 'Cyclone Dance', desc: 'Spin for two seconds, repeatedly hitting and briefly knocking up nearby enemies.', cooldown: 78, damage: 320, damageType: 'Physical', isUlt: true },
    primaryColor: '#c084fc', accentColor: '#fbbf24' },
  { id: 'c_monkeyking_dota', name: 'Stonebranch', displayName: 'Primate Minister', title: 'The Canopy Brother', basis: 'Monkey King (Dota 2)',
    primaryRole: 'Fighter', secondaryRole: 'Assassin', archetype: 'Canopy Carry',
    combatRoles: { Carry: 2, Initiator: 2, Escape: 2, Jungler: 2 },
    hp: 1080, ad: 86, armor: 38, mr: 35, aspd: 0.78, range: 1.9,
    passiveDesc: 'Branch Oath: Stonebranch watches for openings beside his brother Cloudtail.',
    skill1: { name: 'Skyroot Strike', desc: 'Slam an extended staff through a short line and stun enemies it crosses.', cooldown: 9, damage: 170, damageType: 'Physical' },
    skill2: { name: 'Canopy Bound', desc: 'Leap through the trees toward an enemy and land with an area strike.', cooldown: 12, damage: 105, damageType: 'Physical' },
    ultimate: { name: 'Court of Branches', desc: 'Summon a stationary circle of staff-wielding echoes that strike enemies entering it.', cooldown: 82, damage: 360, damageType: 'Physical', isUlt: true },
    primaryColor: '#a16207', accentColor: '#86efac' }
];
