import type { ChampionKit, CoachCard, EvolutionPlan, Facility, PlayerCard } from './types';
import { createResearchedCards } from './rosterResearch.ts';
import { ADDITIONAL_CHAMPIONS } from './additionalChampions.ts';

const BASE_PLAYERS: PlayerCard[] = [
  // === STARTING FIVE (TOP, JUNGLE, MID, BOT, SUPPORT) ===
  {
    id: 'p_thespicy',
    name: 'TheSpicy',
    realName: 'TheShy',
    origin: 'LoL',
    role: 'Fighter',
    preferredRole: 'Fighter',
    tier: 'Diamond',
    ovr: 91,
    stats: { lan: 96, tf: 95, iq: 85, clu: 91, sta: 87, flx: 88 },
    personality: 'Solo Carry',
    badges: ['Aggro Diver', 'Laning Demon'],
    signatureChampions: ['Valkira', 'Kazemaru'],
    morale: 88,
    fatigue: 25,
    level: 40,
    currentXp: 600,
    maxXp: 4000,
    avatarSvg: 'theshy'
  },
  {
    id: 'p_p1mple',
    name: 'p1mple',
    realName: 's1mple',
    origin: 'CS',
    role: 'Assassin',
    preferredRole: 'Assassin',
    tier: 'GOAT',
    ovr: 97,
    stats: { lan: 99, tf: 97, iq: 95, clu: 99, sta: 90, flx: 93 },
    personality: 'Solo Carry',
    badges: ['One-Tap God', 'Clutch King'],
    signatureChampions: ['Kage', 'Buck'],
    morale: 92,
    fatigue: 15,
    level: 52,
    currentXp: 2100,
    maxXp: 5200,
    avatarSvg: 's1mple'
  },
  {
    id: 'p_flaker',
    name: 'Flaker',
    realName: 'Faker',
    origin: 'LoL',
    role: 'Mage',
    preferredRole: 'Mage',
    tier: 'GOAT',
    ovr: 98,
    stats: { lan: 99, tf: 98, iq: 98, clu: 99, sta: 94, flx: 96 },
    personality: 'Stoic Mastermind',
    badges: ['Clutch King', 'Unkillable Demon', 'Baron Steal'],
    signatureChampions: ['Kyumi', 'Kage', 'Raijin'],
    morale: 95,
    fatigue: 10,
    level: 55,
    currentXp: 1200,
    maxXp: 5500,
    avatarSvg: 'faker'
  },
  {
    id: 'p_daft',
    name: 'Daft',
    realName: 'Deft',
    origin: 'LoL',
    role: 'Marksman',
    preferredRole: 'Marksman',
    tier: 'Diamond',
    ovr: 93,
    stats: { lan: 92, tf: 95, iq: 91, clu: 96, sta: 92, flx: 89 },
    personality: 'Clutch Performer',
    badges: ['Clutch King', 'Ice in Veins'],
    signatureChampions: ['Astra', 'Cora', 'Kindra'],
    morale: 90,
    fatigue: 15,
    level: 45,
    currentXp: 950,
    maxXp: 4500,
    avatarSvg: 'deft'
  },
  {
    id: 'p_bigtail',
    name: 'BigTail',
    realName: 'N0tail',
    origin: 'Dota2',
    role: 'Support',
    preferredRole: 'Support',
    tier: 'Diamond',
    ovr: 93,
    stats: { lan: 88, tf: 94, iq: 97, clu: 95, sta: 95, flx: 95 },
    personality: 'Vocal Leader',
    badges: ['Vision Master'],
    signatureChampions: ['Solana', 'Astra'],
    morale: 92,
    fatigue: 14,
    level: 47,
    currentXp: 1400,
    maxXp: 4700,
    avatarSvg: 'notail'
  },

  // === BENCH PLAYERS ===
  {
    id: 'p_craps',
    name: 'Craps',
    realName: 'Caps',
    origin: 'LoL',
    role: 'Mage',
    preferredRole: 'Mage',
    tier: 'Diamond',
    ovr: 92,
    stats: { lan: 93, tf: 94, iq: 90, clu: 91, sta: 88, flx: 95 },
    personality: 'The Showman',
    badges: ['Aggro Diver', 'Golden Flash'],
    signatureChampions: ['Kyumi', 'Valkira', 'Kage'],
    morale: 85,
    fatigue: 20,
    level: 42,
    currentXp: 800,
    maxXp: 4200,
    avatarSvg: 'caps'
  },
  {
    id: 'p_ouzi',
    name: 'Ouzi',
    realName: 'Uzi',
    origin: 'LoL',
    role: 'Marksman',
    preferredRole: 'Marksman',
    tier: 'Diamond',
    ovr: 94,
    stats: { lan: 98, tf: 96, iq: 88, clu: 92, sta: 82, flx: 85 },
    personality: 'Solo Carry',
    badges: ['Laning Demon', 'Hypercarry'],
    signatureChampions: ['Astra', 'Buck', 'Cora'],
    morale: 82,
    fatigue: 30,
    level: 46,
    currentXp: 1100,
    maxXp: 4600,
    avatarSvg: 'uzi'
  },
  {
    id: 'p_neko',
    name: 'NeKo',
    realName: 'NiKo',
    origin: 'CS',
    role: 'Fighter',
    preferredRole: 'Fighter',
    tier: 'Diamond',
    ovr: 91,
    stats: { lan: 97, tf: 93, iq: 89, clu: 91, sta: 89, flx: 88 },
    personality: 'Tilt-Prone Grinder',
    badges: ['One-Tap God'],
    signatureChampions: ['Buck', 'Valkira', 'Kazemaru'],
    morale: 78,
    fatigue: 35,
    level: 38,
    currentXp: 400,
    maxXp: 3800,
    avatarSvg: 'niko'
  },
  {
    id: 'p_woozy',
    name: 'Zypoo',
    realName: 'ZywOo',
    origin: 'CS',
    role: 'Fighter',
    preferredRole: 'Fighter',
    tier: 'Diamond',
    ovr: 95,
    stats: { lan: 96, tf: 96, iq: 95, clu: 95, sta: 95, flx: 96 },
    personality: 'Laid Back',
    badges: ['Ice in Veins', 'Clutch King'],
    signatureChampions: ['Buck', 'Kyumi', 'Sylla'],
    morale: 95,
    fatigue: 5,
    level: 48,
    currentXp: 1800,
    maxXp: 4800,
    avatarSvg: 'zywoo'
  },
  {
    id: 'p_mirecle',
    name: 'Mirecle',
    realName: 'Miracle-',
    origin: 'Dota2',
    role: 'Assassin',
    preferredRole: 'Assassin',
    tier: 'GOAT',
    ovr: 97,
    stats: { lan: 98, tf: 99, iq: 97, clu: 98, sta: 92, flx: 98 },
    personality: 'Clutch Performer',
    badges: ['Clutch King', 'Unkillable Demon'],
    signatureChampions: ['Xin', 'Inai', 'Kage'],
    morale: 94,
    fatigue: 12,
    level: 54,
    currentXp: 3000,
    maxXp: 5400,
    avatarSvg: 'miracle'
  },
  {
    id: 'p_godson',
    name: 'Godson',
    realName: 'Topson',
    origin: 'Dota2',
    role: 'Mage',
    preferredRole: 'Mage',
    tier: 'Diamond',
    ovr: 93,
    stats: { lan: 92, tf: 96, iq: 96, clu: 95, sta: 91, flx: 99 },
    personality: 'The Showman',
    badges: ['Aggro Diver'],
    signatureChampions: ['Raijin', 'Tequoia', 'Kyumi'],
    morale: 90,
    fatigue: 18,
    level: 43,
    currentXp: 900,
    maxXp: 4300,
    avatarSvg: 'topson'
  },
  {
    id: 'p_dns',
    name: 'DNS',
    realName: 'FNS',
    origin: 'Valorant',
    role: 'Support',
    preferredRole: 'Support',
    tier: 'Diamond',
    ovr: 90,
    stats: { lan: 82, tf: 91, iq: 99, clu: 96, sta: 94, flx: 92 },
    personality: 'Mastermind Shotcaller',
    badges: ['Vision Master', 'Clutch King'],
    signatureChampions: ['Solana', 'Zal', 'Renn'],
    morale: 92,
    fatigue: 10,
    level: 41,
    currentXp: 750,
    maxXp: 4100,
    avatarSvg: 'fns'
  },
  {
    id: 'p_penz',
    name: 'PenZ',
    realName: 'TenZ',
    origin: 'Valorant',
    role: 'Marksman',
    preferredRole: 'Marksman',
    tier: 'Diamond',
    ovr: 92,
    stats: { lan: 97, tf: 92, iq: 88, clu: 90, sta: 89, flx: 91 },
    personality: 'The Showman',
    badges: ['One-Tap God', 'Golden Flash'],
    signatureChampions: ['Astra', 'Buck', 'Kindra'],
    morale: 88,
    fatigue: 22,
    level: 44,
    currentXp: 1300,
    maxXp: 4400,
    avatarSvg: 'tenz'
  },
  {
    id: 'p_toaster',
    name: 'Toaster',
    realName: 'Boaster',
    origin: 'Valorant',
    role: 'Support',
    preferredRole: 'Support',
    tier: 'Gold',
    ovr: 82,
    stats: { lan: 78, tf: 85, iq: 90, clu: 85, sta: 92, flx: 88 },
    personality: 'The Showman',
    badges: ['Vision Master'],
    signatureChampions: ['Solana', 'Renn', 'Zal'],
    morale: 96,
    fatigue: 8,
    level: 30,
    currentXp: 400,
    maxXp: 3000,
    avatarSvg: 'boaster'
  },
  {
    id: 'p_pixelrookie',
    name: 'PixelRookie',
    realName: 'Amateur Talent',
    origin: 'LoL',
    role: 'Tank',
    preferredRole: 'Tank',
    tier: 'Bronze',
    ovr: 54,
    stats: { lan: 52, tf: 54, iq: 50, clu: 48, sta: 55, flx: 50 },
    personality: 'Laid Back',
    badges: [],
    signatureChampions: ['Solana', 'Kaolin'],
    morale: 75,
    fatigue: 10,
    level: 10,
    currentXp: 50,
    maxXp: 1000,
    avatarSvg: 'rookie1'
  },
  {
    id: 'p_turbogamer',
    name: 'TurboGamer',
    realName: 'SoloQ Phenom',
    origin: 'LoL',
    role: 'Assassin',
    preferredRole: 'Assassin',
    tier: 'Silver',
    ovr: 66,
    stats: { lan: 68, tf: 65, iq: 64, clu: 66, sta: 67, flx: 62 },
    personality: 'Tilt-Prone Grinder',
    badges: ['Laning Demon'],
    signatureChampions: ['Kage', 'Kazemaru'],
    morale: 80,
    fatigue: 15,
    level: 18,
    currentXp: 200,
    maxXp: 1800,
    avatarSvg: 'rookie2'
  }
];

export const INITIAL_PLAYERS: PlayerCard[] = [...BASE_PLAYERS, ...createResearchedCards(BASE_PLAYERS)].map(p => ({
  ...p,
  playableRoles: p.playableRoles || [p.preferredRole || p.role || 'Mage']
}));

export const INITIAL_COACHES: CoachCard[] = [
  {
    id: 'c_kkopa',
    name: 'KkOpa',
    realName: 'kkOma',
    tier: 'GOAT',
    style: 'Objective Macro',
    chemistryBonus: 15,
    playbookBonus: 12,
    extraBans: 1,
    quote: 'Listen to the belt, lift the World Trophy.',
    avatarSvg: 'kkoma'
  },
  {
    id: 'c_mastermind',
    name: 'MasterMind',
    realName: 'Reeves',
    tier: 'Diamond',
    style: 'Dynamic Adapt',
    chemistryBonus: 12,
    playbookBonus: 10,
    extraBans: 1,
    quote: 'Every outcome has already been computed.',
    avatarSvg: 'mastermind'
  },
  {
    id: 'c_bbaegi',
    name: 'Bbaegi',
    realName: 'Bengi',
    tier: 'Diamond',
    style: 'Aggressive Dive',
    chemistryBonus: 10,
    playbookBonus: 8,
    extraBans: 0,
    quote: 'The lane is always ours to gank.',
    avatarSvg: 'bengi'
  }
];

export const CHAMPIONS: ChampionKit[] = [
  // 1. Solana (Leona - LoL)
  {
    id: 'c_solana',
    name: 'Solana',
    displayName: 'Dawnna',
    title: 'The Sun Vanguard',
    basis: 'Leona',
    primaryRole: 'Tank',
    secondaryRole: 'Support',
    archetype: 'Vanguard Tank',
    hp: 1250,
    ad: 55,
    armor: 55,
    mr: 48,
    aspd: 0.65,
    range: 1.5,
    passiveDesc: 'Sunlight Mark: Marks struck enemies; allies trigger marks for +45 magic damage.',
    skill1: { name: 'Solar Shieldbash', desc: 'Stuns target for 1.2s & grants 180 HP solar shield (+18% AD, +25% AP).', cooldown: 6, damage: 80, damageType: 'Magic' },
    skill2: { name: 'Zenith Lance', desc: 'Roots target and dashes Solana directly to them (+18% AD, +25% AP).', cooldown: 8, damage: 110, damageType: 'Magic' },
    ultimate: { name: 'Daybreak Flare', desc: 'Giant solar beam! Stuns center cluster for 2.0s and slows by 60% (+18% AD, +25% AP).', cooldown: 55, damage: 320, damageType: 'Magic', isUlt: true },
    primaryColor: '#f59e0b',
    accentColor: '#fbbf24'
  },
  // 2. Astra (Ashe - LoL)
  {
    id: 'c_astra',
    name: 'Astra',
    displayName: 'Aiselle',
    title: 'The Frost Sovereign',
    basis: 'Ashe',
    primaryRole: 'Marksman',
    secondaryRole: 'Support',
    archetype: 'Utility Marksman',
    hp: 780,
    ad: 75,
    armor: 28,
    mr: 30,
    aspd: 0.85,
    range: 6.0,
    passiveDesc: 'Glacial Bite: Basic attacks apply a stacking 25% chill slow.',
    skill1: { name: 'Volley Cone', desc: 'Fires 7 frost arrows in a wide forward cone, slowing targets (+36% AD, +25% AP).', cooldown: 6, damage: 110, damageType: 'Physical' },
    skill2: { name: 'Frost Flurry', desc: '+50% Attack speed & 5-arrow flurry barrage for 4s (+36% AD, +25% AP).', cooldown: 8, damage: 140, damageType: 'Physical' },
    ultimate: { name: 'Enchanted Crystal Comet', desc: 'Global lane ice arrow! Stuns primary target for 2.5s (+36% AD, +25% AP).', cooldown: 60, damage: 350, damageType: 'Magic', isUlt: true },
    primaryColor: '#38bdf8',
    accentColor: '#93c5fd'
  },
  // 3. Kyumi (Ahri - LoL)
  {
    id: 'c_kyumi',
    name: 'Kyumi',
    displayName: 'Vixelle',
    title: 'The Nine-Tailed Spirit',
    basis: 'Ahri',
    primaryRole: 'Mage',
    secondaryRole: 'Assassin',
    archetype: 'Burst Mage',
    hp: 820,
    ad: 60,
    armor: 30,
    mr: 32,
    aspd: 0.70,
    range: 5.5,
    passiveDesc: 'Essence Feast: Restores 12% missing HP after landing combos or scoring takedowns.',
    skill1: { name: 'Orb of Illusion', desc: 'Throws magic orb forward, returning with pure TRUE DAMAGE (+18% AD, +42% AP).', cooldown: 5, damage: 135, damageType: 'True' },
    skill2: { name: 'Charm of Longing', desc: 'Charms enemy for 1.4s, forcing them to walk harmlessly toward Kyumi (+18% AD, +42% AP).', cooldown: 9, damage: 90, damageType: 'Magic' },
    ultimate: { name: 'Spirit Rush', desc: 'Triple dash firing homing spirit bolts at low HP enemies (+18% AD, +42% AP).', cooldown: 55, damage: 380, damageType: 'Magic', isUlt: true },
    primaryColor: '#ec4899',
    accentColor: '#f472b6'
  },
  // 4. Buck (Graves - LoL)
  {
    id: 'c_buck',
    name: 'Buck',
    displayName: 'Gritlock',
    title: 'The Boomstick Outlaw',
    basis: 'Graves',
    primaryRole: 'Marksman',
    secondaryRole: 'Fighter',
    archetype: 'Skirmish Bruiser',
    hp: 920,
    ad: 88,
    armor: 42,
    mr: 35,
    aspd: 0.72,
    range: 3.5,
    passiveDesc: '12-Gauge Double Barrel: Attacks fire 4 shotgun pellets. Stacking attacks grant +15 Armor.',
    skill1: { name: 'Powder Keg Blast', desc: 'Explosive shell detonating in an explosive T-shape AOE (+36% AD, +25% AP).', cooldown: 6, damage: 165, damageType: 'Physical' },
    skill2: { name: 'Smoke Screen', desc: 'Deploys smoke cloud that blinds enemies and limits attack range to melee (+36% AD, +25% AP).', cooldown: 10, damage: 60, damageType: 'Magic' },
    ultimate: { name: 'Collateral Blast', desc: 'Devastating recoil shell blasting front cone and propelling Buck back (+36% AD, +25% AP).', cooldown: 55, damage: 440, damageType: 'Physical', isUlt: true },
    primaryColor: '#d97706',
    accentColor: '#78350f'
  },
  // 5. Valkira (Ambessa / Riven - LoL)
  {
    id: 'c_valkira',
    name: 'Valkira',
    displayName: 'Bessara',
    title: 'The Warlord Matriarch',
    basis: 'Ambessa',
    primaryRole: 'Fighter',
    secondaryRole: 'Assassin',
    archetype: 'Skirmisher Bruiser',
    hp: 980,
    ad: 82,
    armor: 40,
    mr: 36,
    aspd: 0.80,
    range: 2.0,
    passiveDesc: "Drakehound's Step: Dashes after casting any skill with empowered reach & bleed.",
    skill1: { name: 'Crescent Cleave', desc: 'Sweeps twin blades. Outer edge hit deals double damage & deep bleed (+36% AD, +25% AP).', cooldown: 5, damage: 155, damageType: 'Physical' },
    skill2: { name: 'Iron Will Slam', desc: 'Slams blades into the ground for a 200 HP shield and shockwave (+36% AD, +25% AP).', cooldown: 7, damage: 100, damageType: 'Physical' },
    ultimate: { name: "Executioner's Descent", desc: 'Teleports behind lowest-HP enemy, suppressing and slamming for lethal execute (+36% AD, +25% AP).', cooldown: 60, damage: 460, damageType: 'Physical', isUlt: true },
    primaryColor: '#dc2626',
    accentColor: '#991b1b'
  },
  // 6. Kage (Zed - LoL)
  {
    id: 'c_kage',
    name: 'Kage',
    displayName: 'Vanta',
    title: 'The Master of Shadows',
    basis: 'Zed',
    primaryRole: 'Assassin',
    secondaryRole: 'Fighter',
    archetype: 'Shadow Assassin',
    hp: 860,
    ad: 84,
    armor: 36,
    mr: 32,
    aspd: 0.78,
    range: 1.8,
    passiveDesc: 'Dusk Execution: Basic attacks against targets below 50% HP deal +12% maximum HP as bonus magic damage.',
    skill1: { name: 'Shadow Shuriken', desc: 'Hurls spinning crimson shurikens in a line dealing heavy physical damage (+36% AD, +25% AP).', cooldown: 5, damage: 165, damageType: 'Physical' },
    skill2: { name: 'Shadow Projection', desc: 'Summons a shadow clone that mimics abilities and allows instant swapping (+36% AD, +25% AP).', cooldown: 12, damage: 70, damageType: 'Physical' },
    ultimate: { name: 'Eclipse Mark', desc: 'Teleports behind victim with crimson death marks, detonating for massive mirror execute after 3s (+36% AD, +25% AP).', cooldown: 65, damage: 460, damageType: 'Physical', isUlt: true },
    primaryColor: '#b91c1c',
    accentColor: '#450a0a'
  },
  // 7. Kazemaru (Yasuo - LoL)
  {
    id: 'c_kazemaru',
    name: 'Kazemaru',
    displayName: 'Galejandro',
    title: 'The Wandering Tempest',
    basis: 'Yasuo',
    primaryRole: 'Fighter',
    secondaryRole: 'Assassin',
    archetype: 'Wind Skirmisher',
    hp: 920,
    ad: 78,
    armor: 38,
    mr: 34,
    aspd: 0.82,
    range: 2.0,
    passiveDesc: 'Gale Walker: Critical strike chance is doubled. Generates a 220 HP wind shield upon taking damage.',
    skill1: { name: 'Tempest Thrust & Gale', desc: 'Thrusts katana forward; launches a howling blue tornado that knocks up enemies for 1.5s (+36% AD, +25% AP).', cooldown: 4, damage: 145, damageType: 'Physical' },
    skill2: { name: 'Zephyr Barrier', desc: 'Erects a shimmering wall of gusting wind that disintegrates incoming enemy projectiles for 3.5s.', cooldown: 14, damage: 0, damageType: 'Physical' },
    ultimate: { name: 'Airborne Sever', desc: 'Blinks to airborne enemies, suspending them mid-air for 5 golden blade slashes and 50% armor shred (+36% AD, +25% AP).', cooldown: 55, damage: 430, damageType: 'Physical', isUlt: true },
    primaryColor: '#0284c7',
    accentColor: '#38bdf8'
  },
  // 8. Kindra & Grim (Kindred - LoL)
  {
    id: 'c_kindra',
    name: 'Kindra',
    displayName: 'Lambent',
    title: 'The Eternal Hunters',
    basis: 'Kindred',
    primaryRole: 'Marksman',
    secondaryRole: 'Assassin',
    archetype: 'Spectral Marksman',
    hp: 810,
    ad: 74,
    armor: 32,
    mr: 30,
    aspd: 0.84,
    range: 5.5,
    passiveDesc: 'Spirit Mark: Hunting jungle camps and low HP champions increases attack range and damage by +15%.',
    skill1: { name: 'Ghoststep Volley', desc: 'Vaults gracefully and fires 3 spectral purple arrows at the 3 closest enemies (+36% AD, +25% AP).', cooldown: 5, damage: 135, damageType: 'Physical' },
    skill2: { name: 'Shadow Pounce', desc: 'Claims a spirit territory where shadowy Wolf furiously lunges and bites enemies (+36% AD, +25% AP).', cooldown: 10, damage: 110, damageType: 'Magic' },
    ultimate: { name: 'Sanctuary of Eternity', desc: 'Blesses a radiant golden sanctuary: no unit inside can fall below 10% HP, healing allies by 450 HP on expiry!', cooldown: 75, damage: 0, damageType: 'True', isUlt: true },
    primaryColor: '#8b5cf6',
    accentColor: '#4c1d95'
  },
  // 9. Cora (Xayah - LoL)
  {
    id: 'c_cora',
    name: 'Cora',
    displayName: 'Plumeira',
    title: 'The Rebel Feather',
    basis: 'Xayah',
    primaryRole: 'Marksman',
    secondaryRole: 'Assassin',
    archetype: 'Feather Marksman',
    hp: 800,
    ad: 76,
    armor: 30,
    mr: 30,
    aspd: 0.82,
    range: 5.5,
    passiveDesc: 'Quill Ricochet: Attacks pass through targets and leave piercing magenta quill feathers embedded on the ground.',
    skill1: { name: 'Twin Plumage', desc: 'Flings two penetrating quill feathers in a line that plant in the ground (+36% AD, +25% AP).', cooldown: 6, damage: 140, damageType: 'Physical' },
    skill2: { name: 'Feather Recall', desc: 'Recalls all ground feathers back to her hands; hitting enemies with 3+ feathers roots them for 1.3s! (+36% AD, +25% AP).', cooldown: 8, damage: 190, damageType: 'Physical' },
    ultimate: { name: 'Skyward Plumes', desc: 'Leaps untargetable into the air and rains down 5 piercing quills in a crescent fan (+36% AD, +25% AP).', cooldown: 65, damage: 380, damageType: 'Physical', isUlt: true },
    primaryColor: '#d946ef',
    accentColor: '#a21caf'
  },
  // 10. Renn (Rakan - LoL)
  {
    id: 'c_renn',
    name: 'Renn',
    displayName: 'Gildan',
    title: 'The Battle Dancer',
    basis: 'Rakan',
    primaryRole: 'Support',
    secondaryRole: 'Tank',
    archetype: 'Initiator Support',
    hp: 960,
    ad: 58,
    armor: 46,
    mr: 42,
    aspd: 0.68,
    range: 2.2,
    passiveDesc: 'Gilded Cloak: Periodically gains a 180 HP glowing feathered cloak shield.',
    skill1: { name: 'Gilded Vault', desc: 'Dashes forward and leaps into the air, knocking up all enemies in a 75px radius for 1.2s (+18% AD, +25% AP).', cooldown: 9, damage: 115, damageType: 'Magic' },
    skill2: { name: 'Harmonic Waltz', desc: 'Dashes to an allied champion, granting both a 220 HP golden feathered shield.', cooldown: 8, damage: 0, damageType: 'Magic' },
    ultimate: { name: 'Dazzling Rush', desc: 'Cloaks in hypnotic golden light with +80% speed, charming all enemies he touches for 1.5s! (+18% AD, +25% AP).', cooldown: 65, damage: 290, damageType: 'Magic', isUlt: true },
    primaryColor: '#f59e0b',
    accentColor: '#d97706'
  },
  // 11. Sylla (Lone Druid - Dota 2)
  {
    id: 'c_sylla',
    name: 'Sylla',
    displayName: 'Sylvan Solo',
    title: 'The Bear Shaman',
    basis: 'Lone Druid',
    primaryRole: 'Fighter',
    secondaryRole: 'Marksman',
    archetype: 'Summoner Bruiser',
    hp: 880,
    ad: 70,
    armor: 36,
    mr: 34,
    aspd: 0.72,
    range: 4.5,
    passiveDesc: 'Entangling Claws: Attacks have a 20% chance to summon emerald roots holding the target immobile for 1.5s.',
    skill1: { name: 'Summon Spirit Bear', desc: 'Summons an armored Spirit Bear companion (1800 HP) that charges and brawls alongside him (+36% AD, +25% AP).', cooldown: 18, damage: 130, damageType: 'Physical' },
    skill2: { name: 'Savage Roar', desc: 'Sylla and his bear unleash an emerald sonic roar, terrifying nearby enemies to flee for 1.3s (+36% AD, +25% AP).', cooldown: 12, damage: 80, damageType: 'Magic' },
    ultimate: { name: 'True Form', desc: 'Transforms into a gargantuan Ironclaw Bear, gaining +450 Shield, +20 Armor, and cleaving melee sweeps for 12s (+36% AD, +25% AP).', cooldown: 70, damage: 340, damageType: 'Physical', isUlt: true },
    primaryColor: '#15803d',
    accentColor: '#166534'
  },
  // 12. Tequoia (Nature's Prophet / Furion - Dota 2)
  {
    id: 'c_tequoia',
    name: 'Tequoia',
    displayName: 'Fernanda',
    title: "Nature's Sovereign",
    basis: 'Furion',
    primaryRole: 'Mage',
    secondaryRole: 'Marksman',
    archetype: 'Zone Control Mage',
    hp: 840,
    ad: 65,
    armor: 32,
    mr: 34,
    aspd: 0.76,
    range: 5.8,
    passiveDesc: 'Forest Guardian: Every 4th attack blooms an emerald seed that restores 50 HP and roots minions.',
    skill1: { name: 'Verdant Cage', desc: 'Encircles the target champion in a ring of 8 living oak trees, trapping them inside for 2.8s! (+18% AD, +42% AP).', cooldown: 10, damage: 90, damageType: 'Magic' },
    skill2: { name: 'Nature Link', desc: 'Link enemy champions in a zone for 4 seconds. When one takes health damage, each other linked enemy takes 10% of it as true damage.', cooldown: 11, damage: 0, damageType: 'Magic' },
    ultimate: { name: "Nature's Wrath", desc: 'Releases a bouncing green solar lightning sphere that leaps up to 10 times with escalating damage! (+18% AD, +42% AP).', cooldown: 65, damage: 410, damageType: 'Magic', isUlt: true },
    primaryColor: '#22c55e',
    accentColor: '#14532d'
  },
  // 13. Zal (Dazzle - Dota 2)
  {
    id: 'c_zal',
    name: 'Zal',
    displayName: 'Glimmerick',
    title: 'The Shadow Priest',
    basis: 'Dazzle',
    primaryRole: 'Support',
    secondaryRole: 'Mage',
    archetype: 'Lifebinder Support',
    hp: 830,
    ad: 56,
    armor: 34,
    mr: 38,
    aspd: 0.70,
    range: 5.2,
    passiveDesc: 'Weave: Casting abilities shreds nearby enemy armor while fortifying ally armor by +15.',
    skill1: { name: 'Venom Hex', desc: 'Spits deep violet venom in a cone that poisons targets and slows them by up to 50% (+18% AD, +42% AP).', cooldown: 7, damage: 130, damageType: 'Magic' },
    skill2: { name: 'Shadow Surge', desc: 'Chains vibrant pink healing lightning through allies (+180 HP) that zaps adjacent enemies! (+18% AD, +42% AP).', cooldown: 6, damage: 120, damageType: 'Magic' },
    ultimate: { name: 'Soul Sanctuary', desc: 'Projects a luminous pink cross over lowest-HP ally: they cannot die and cannot fall below 1 HP for 4.5s!', cooldown: 70, damage: 0, damageType: 'True', isUlt: true },
    primaryColor: '#ec4899',
    accentColor: '#9d174d'
  },
  // 14. Xin (Ember Spirit - Dota 2)
  {
    id: 'c_xin',
    name: 'Xin',
    displayName: 'Cindergent',
    title: 'The Ember Spirit',
    basis: 'Ember Spirit',
    primaryRole: 'Fighter',
    secondaryRole: 'Assassin',
    archetype: 'Flame Skirmisher',
    hp: 910,
    ad: 80,
    armor: 38,
    mr: 34,
    aspd: 0.80,
    range: 2.0,
    passiveDesc: 'Flame Guard: Shrouds Xin in blazing fire that absorbs 200 magic damage and burns nearby foes.',
    skill1: { name: 'Blazing Bolas', desc: 'Flings flaming bolas that wrap around 2 nearby enemies, burning and rooting them for 1.8s (+36% AD, +25% AP).', cooldown: 7, damage: 140, damageType: 'Magic' },
    skill2: { name: 'Flash Flurry', desc: 'Dashes through all enemies in a 90px fiery circle in milliseconds with critical slashes before returning! (+36% AD, +25% AP).', cooldown: 6, damage: 160, damageType: 'Physical' },
    ultimate: { name: 'Flame Remnant Charge', desc: 'Drops blazing statues and rocket-dashes through them with fiery shockwave explosions! (+36% AD, +25% AP).', cooldown: 55, damage: 440, damageType: 'Magic', isUlt: true },
    primaryColor: '#ea580c',
    accentColor: '#9a3412'
  },
  // 15. Raijin (Storm Spirit - Dota 2)
  {
    id: 'c_raijin',
    name: 'Raijin',
    displayName: 'Voltaire',
    title: 'The Storm Spirit',
    basis: 'Storm Spirit',
    primaryRole: 'Mage',
    secondaryRole: 'Assassin',
    archetype: 'Lightning Burst Mage',
    hp: 820,
    ad: 60,
    armor: 32,
    mr: 32,
    aspd: 0.74,
    range: 5.0,
    passiveDesc: 'Overload: Casting any spell charges next attack with an electric burst slowing and dealing +60 AOE magic damage.',
    skill1: { name: 'Static Remnant', desc: 'Leaves a crackling electrical duplicate that detonates when enemies approach (+18% AD, +42% AP).', cooldown: 4, damage: 140, damageType: 'Magic' },
    skill2: { name: 'Electric Vortex', desc: 'Channels a lightning tether that pulls an enemy champion helplessly toward him for 1.4s (+18% AD, +42% AP).', cooldown: 11, damage: 75, damageType: 'Magic' },
    ultimate: { name: 'Ball Lightning', desc: 'Rushes as lightning toward a chosen ground position or facing direction, even without an enemy unit target (+18% AD, +42% AP).', cooldown: 3, damage: 420, damageType: 'Magic', isUlt: true, targeting: 'ground' },
    primaryColor: '#06b6d4',
    accentColor: '#0891b2'
  },
  // 16. Kaolin (Earth Spirit - Dota 2)
  {
    id: 'c_kaolin',
    name: 'Kaolin',
    displayName: 'TerraByte',
    title: 'The Earth Spirit',
    basis: 'Earth Spirit',
    primaryRole: 'Tank',
    secondaryRole: 'Fighter',
    archetype: 'Earth Brawler Tank',
    hp: 1180,
    ad: 66,
    armor: 52,
    mr: 46,
    aspd: 0.65,
    range: 1.8,
    passiveDesc: 'Stone Remnant: Periodically stores stone remnants that can be smashed, pulled, or rolled through.',
    skill1: { name: 'Boulder Smash', desc: 'Kicks a giant jade boulder across 220px, shattering and stunning all struck enemies for 1.5s (+18% AD, +25% AP).', cooldown: 8, damage: 135, damageType: 'Magic' },
    skill2: { name: 'Rolling Boulder', desc: 'Curls into a rolling jade stone ball, crashing into enemies for knockback and gaining a 160 HP shield (+18% AD, +25% AP).', cooldown: 7, damage: 105, damageType: 'Physical' },
    ultimate: { name: 'Magnetize', desc: 'Infects nearby enemies with jade magnetic resonance, pulsing continuous shockwaves for 6s! (+18% AD, +25% AP).', cooldown: 65, damage: 370, damageType: 'Magic', isUlt: true },
    primaryColor: '#059669',
    accentColor: '#064e3b'
  },
  // 17. Inai (Void Spirit - Dota 2)
  {
    id: 'c_inai',
    name: 'Inai',
    displayName: 'Nulliver',
    title: 'The Void Spirit',
    basis: 'Void Spirit',
    primaryRole: 'Assassin',
    secondaryRole: 'Mage',
    archetype: 'Void Infiltrator',
    hp: 870,
    ad: 78,
    armor: 36,
    mr: 34,
    aspd: 0.78,
    range: 2.2,
    passiveDesc: 'Astral Resonance: Hitting abilities grants a physical barrier absorbing 140 damage.',
    skill1: { name: 'Aether Remnant', desc: 'Deploys a purple void spirit watcher that pulls enemies across its gaze toward it for 1.4s (+36% AD, +42% AP).', cooldown: 8, damage: 125, damageType: 'Magic' },
    skill2: { name: 'Dissimilate', desc: 'Disappears into 7 void portals and crashes down at target portal location in an astral explosion (+36% AD, +42% AP).', cooldown: 10, damage: 150, damageType: 'Magic' },
    ultimate: { name: 'Astral Step', desc: 'Instantly teleports and slashes through enemies in a line, marking them with an astral rift that detonates for heavy execute! (+36% AD, +42% AP).', cooldown: 60, damage: 450, damageType: 'Magic', isUlt: true },
    primaryColor: '#7c3aed',
    accentColor: '#4c1d95'
  },
  ...ADDITIONAL_CHAMPIONS
];

export const INITIAL_FACILITIES: Facility[] = [
  { id: 'f_scrim', name: 'PC Scrim Battle-Station', level: 1, maxLevel: 5, cost: 1000, desc: '+XP & Team Synergy drills', icon: 'monitor' },
  { id: 'f_vod', name: 'Tactical VOD & Playbook Room', level: 1, maxLevel: 5, cost: 1000, desc: '+Macro Game IQ & Counter-drafts', icon: 'brain' },
  { id: 'f_gym', name: 'Ergonomic Gym & Physio', level: 1, maxLevel: 5, cost: 1200, desc: 'Heals wrist strain & reduces tilt', icon: 'dumbbell' },
  { id: 'f_stream', name: 'RGB Creator Stream Studio', level: 1, maxLevel: 5, cost: 1500, desc: 'Generates sponsorship coins', icon: 'video' },
  { id: 'f_kitchen', name: 'Gourmet Cafeteria', level: 1, maxLevel: 5, cost: 1200, desc: 'Boosts Daily Energy & Mood', icon: 'utensils' },
  { id: 'f_beds', name: 'Soundproof Sleep Pods', level: 1, maxLevel: 5, cost: 1000, desc: 'Fast fatigue recovery after Bo5 series', icon: 'bed' }
];

export const INITIAL_EVOLUTIONS: EvolutionPlan[] = [
  // --- EA FC ROLE VERSATILITY EVOLUTIONS ---
  {
    id: 'evo_role_marksman',
    name: 'Role Evolution: Marksman Adaptation',
    desc: 'Train your player in lethal ranged kiting and carry precision. Unlocks Marksman role proficiency and adds a signature marksman.',
    maxTier: 'GOAT',
    maxOvr: 96,
    coinCost: 1200,
    targetTier: 'Diamond',
    ovrBoost: 5,
    statBoost: { lan: 8, clu: 7, flx: 14, tf: 5 },
    unlockedBadge: '✦ Apex Sharpshooter',
    unlockedRole: 'Marksman',
    selectableSignatures: ['Jinxy', 'Astra', 'Cora', 'Aetherbolt', 'Corsara'],
    objectives: [
      { id: 'obj_1', desc: 'Deploy player in 1 Clash Arena match', target: 1, current: 0, completed: false },
      { id: 'obj_2', desc: 'Secure 3 team takedowns in the match', target: 3, current: 0, completed: false }
    ]
  },
  {
    id: 'evo_role_support',
    name: 'Role Evolution: Support Tactician',
    desc: 'Master warding, initiation, peel, and defensive shields. Unlocks Support role proficiency and adds a signature support avatar.',
    maxTier: 'GOAT',
    maxOvr: 96,
    coinCost: 1200,
    targetTier: 'Diamond',
    ovrBoost: 5,
    statBoost: { iq: 9, tf: 7, flx: 14, sta: 6 },
    unlockedBadge: '✦ Guardian Angel',
    unlockedRole: 'Support',
    selectableSignatures: ['Aetheris', 'Wraithhook', 'Voltgrip', 'Renn', 'Solenne'],
    objectives: [
      { id: 'obj_1', desc: 'Deploy player in 1 Clash Arena match', target: 1, current: 0, completed: false },
      { id: 'obj_2', desc: 'Support 5 takedowns or structure sieges', target: 5, current: 0, completed: false }
    ]
  },
  {
    id: 'evo_role_mage',
    name: 'Role Evolution: Arcane Maestro',
    desc: 'Master zone control, high burst magic and wave management. Unlocks Mage role proficiency and adds a signature mage avatar.',
    maxTier: 'GOAT',
    maxOvr: 96,
    coinCost: 1200,
    targetTier: 'Diamond',
    ovrBoost: 5,
    statBoost: { tf: 8, iq: 7, flx: 14, lan: 6 },
    unlockedBadge: '✦ Arcane Genius',
    unlockedRole: 'Mage',
    selectableSignatures: ['Kaelen', 'Hweilin', 'Paxi', 'Kyumi', 'Raijin'],
    objectives: [
      { id: 'obj_1', desc: 'Deploy player in 1 Clash Arena match', target: 1, current: 0, completed: false },
      { id: 'obj_2', desc: 'Score 1 spell takedown or match win', target: 1, current: 0, completed: false }
    ]
  },
  {
    id: 'evo_role_tank',
    name: 'Role Evolution: Frontline Bulwark',
    desc: 'Develop indestructible stamina and bodyblock mechanics. Unlocks Tank role proficiency and adds a signature tank avatar.',
    maxTier: 'GOAT',
    maxOvr: 96,
    coinCost: 1200,
    targetTier: 'Diamond',
    ovrBoost: 5,
    statBoost: { sta: 10, tf: 7, flx: 14, clu: 5 },
    unlockedBadge: '✦ Iron Fortress',
    unlockedRole: 'Tank',
    selectableSignatures: ['Quillback', 'Solana', 'Mirehook', 'Stonewake'],
    objectives: [
      { id: 'obj_1', desc: 'Deploy player in 1 Clash Arena match', target: 1, current: 0, completed: false },
      { id: 'obj_2', desc: 'Withstand 2 tower dives or teamfights', target: 2, current: 0, completed: false }
    ]
  },
  {
    id: 'evo_role_assassin',
    name: 'Role Evolution: Shadow Infiltrator',
    desc: 'Learn lethal flank angles, stealth timings, and target execution. Unlocks Assassin role proficiency and adds a signature assassin.',
    maxTier: 'GOAT',
    maxOvr: 96,
    coinCost: 1200,
    targetTier: 'Diamond',
    ovrBoost: 5,
    statBoost: { lan: 9, clu: 8, flx: 14, tf: 5 },
    unlockedBadge: '✦ Silent Blade',
    unlockedRole: 'Assassin',
    selectableSignatures: ['Kage', 'Inai', 'Veyara', 'Valerie'],
    objectives: [
      { id: 'obj_1', desc: 'Deploy player in 1 Clash Arena match', target: 1, current: 0, completed: false },
      { id: 'obj_2', desc: 'Score 2 kills on enemy backline carries', target: 2, current: 0, completed: false }
    ]
  },
  {
    id: 'evo_role_fighter',
    name: 'Role Evolution: Brawler Warlord',
    desc: 'Excel at close-quarters trading and sustained skirmishes. Unlocks Fighter role proficiency and adds a signature fighter.',
    maxTier: 'GOAT',
    maxOvr: 96,
    coinCost: 1200,
    targetTier: 'Diamond',
    ovrBoost: 5,
    statBoost: { lan: 7, sta: 8, flx: 14, tf: 6 },
    unlockedBadge: '✦ Relentless Bruiser',
    unlockedRole: 'Fighter',
    selectableSignatures: ['Jaxon', 'Valerie', 'Batrix', 'Buck', 'Valkira'],
    objectives: [
      { id: 'obj_1', desc: 'Deploy player in 1 Clash Arena match', target: 1, current: 0, completed: false },
      { id: 'obj_2', desc: 'Clear 3 waves or neutral camps', target: 3, current: 0, completed: false }
    ]
  },

  // --- EA FC TIER ASCENDANCE EVOLUTIONS ---
  {
    id: 'evo_rookie_awakening',
    name: 'Golden Glow-Up: To Gold Tier',
    desc: 'EA FC Golden Glow-Up. Hone a raw Bronze/Silver talent into a certified Gold starting pro with massive attribute boosts.',
    maxTier: 'Silver',
    maxOvr: 75,
    coinCost: 600,
    targetTier: 'Gold',
    ovrBoost: 7,
    statBoost: { lan: 8, tf: 7, iq: 6, clu: 8, sta: 6, flx: 8 },
    unlockedBadge: '✦ Rising Star',
    selectableSignatures: ['Astra', 'Solana', 'Kyumi', 'Buck'],
    objectives: [
      { id: 'obj_1', desc: 'Deploy player in 2 Clash Arena matches', target: 2, current: 0, completed: false },
      { id: 'obj_2', desc: 'Score 5 total team takedowns', target: 5, current: 0, completed: false }
    ]
  },
  {
    id: 'evo_clutch_ascendance',
    name: 'Centurions Upgrade: To Platinum Tier',
    desc: 'EA FC Centurions Upgrade. Elevate a Gold starter into an elite Platinum clutch playmaker with ice in their veins.',
    maxTier: 'Gold',
    maxOvr: 85,
    coinCost: 2000,
    targetTier: 'Platinum',
    ovrBoost: 6,
    statBoost: { lan: 7, tf: 8, iq: 8, clu: 10, sta: 7, flx: 8 },
    unlockedBadge: '✦ Clutch Mastermind',
    selectableSignatures: ['Kazemaru', 'Cora', 'Zal', 'Kage'],
    objectives: [
      { id: 'obj_1', desc: 'Win 2 matches with player in starting lineup', target: 2, current: 0, completed: false },
      { id: 'obj_2', desc: 'Score 8 kills with signature champions', target: 8, current: 0, completed: false }
    ]
  },
  {
    id: 'evo_goat_immortality',
    name: 'The Immortality Path: To GOAT Tier',
    desc: 'The pinnacle of competitive mastery. Elevate a Diamond superstar into an immortal GOAT esports icon.',
    maxTier: 'Diamond',
    maxOvr: 95,
    coinCost: 10000,
    targetTier: 'GOAT',
    ovrBoost: 6,
    statBoost: { lan: 7, tf: 7, iq: 8, clu: 8, sta: 8, flx: 8 },
    unlockedBadge: '✦ Unkillable Demon',
    selectableSignatures: ['Kaelen', 'Flaker', 'Jinxy', 'Valerie', 'Raijin'],
    objectives: [
      { id: 'obj_1', desc: 'Win 3 Split Matches with player in lineup', target: 3, current: 0, completed: false },
      { id: 'obj_2', desc: 'Achieve 1 Match MVP award', target: 1, current: 0, completed: false }
    ]
  }
];
